/// <reference types="node" />

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { getComponentNames } from './shared/names';

const root = resolve(import.meta.dirname, '..');
const names = getComponentNames(process.argv[2]);
const componentDir = resolve(root, 'packages/vue/src/components', names.kebab);
const docsFile = resolve(root, 'docs/components', `${names.kebab}.md`);
const apiFile = resolve(componentDir, 'api.ts');

function writeNewFile(path: string, content: string): void {
  if (existsSync(path)) {
    throw new Error(`Refusing to overwrite existing file: ${path}`);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

writeNewFile(
  resolve(componentDir, `${names.kebab}.vue`),
  `<script setup lang="ts">
import { ${names.pascal}Props } from './props';

defineOptions({
  name: 'Custom${names.pascal}'
});

defineProps(${names.pascal}Props);
</script>

<template>
  <div class="custom-${names.kebab}">
    <slot />
  </div>
</template>
`
);

writeNewFile(
  resolve(componentDir, 'props.ts'),
  `import type { PropType } from 'vue';

export const ${names.pascal}Props = {
  variant: {
    type: String as PropType<'default' | 'primary'>,
    default: 'default'
  }
} as const;
`
);

writeNewFile(
  apiFile,
  `import type { ApiProperty } from '../../scripts-api';

export const api: ApiProperty[] = [
  {
    name: 'variant',
    type: "'default' | 'primary'",
    default: "'default'",
    description: 'Controls the visual variant.'
  }
];
`
);

writeNewFile(
  resolve(componentDir, 'index.ts'),
  `export { default as Custom${names.pascal} } from './${names.kebab}.vue';
export * from './props';
`
);

writeNewFile(
  resolve(componentDir, 'demo/basic.vue'),
  `<script setup lang="ts">
import { Custom${names.pascal} } from '../index';
</script>

<template>
  <Custom${names.pascal}>Basic ${names.pascal}</Custom${names.pascal}>
</template>
`
);

writeNewFile(
  resolve(componentDir, `__tests__/${names.kebab}.test.ts`),
  `import { describe, expect, it } from 'vitest';

import { Custom${names.pascal} } from '../index';

describe('Custom${names.pascal}', () => {
  it('exports the component', () => {
    expect(Custom${names.pascal}).toBeTruthy();
  });
});
`
);

writeNewFile(
  docsFile,
  `# ${names.pascal}

## 基础用法

<!-- DemoBlock wiring is completed by docs-writer after the component implementation is finalized. -->

## API

<!-- API table is generated by pnpm generate-api ${names.pascal}. -->
`
);

const componentIndex = resolve(root, 'packages/vue/src/components/index.ts');
const currentIndex = readFileSync(componentIndex, 'utf8');
const exportLine = `export * from './${names.kebab}';`;

if (!currentIndex.includes(exportLine)) {
  writeFileSync(componentIndex, `${currentIndex.trim()}\n${exportLine}\n`);
}

console.log(`Created component scaffold for ${names.pascal}.`);
