/// <reference types="node" />

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { runCli } from './shared/cli';
import { getComponentNames } from './shared/names';

const root = resolve(import.meta.dirname, '..');

interface TargetFile {
  path: string;
  content: string;
}

function writeTargetFiles(files: TargetFile[]): void {
  const collisions = files.filter(file => existsSync(file.path));

  if (collisions.length > 0) {
    throw new Error(
      `Refusing to create a partial component. Existing files:\n${collisions
        .map(file => `- ${file.path}`)
        .join('\n')}`
    );
  }

  for (const file of files) {
    mkdirSync(dirname(file.path), { recursive: true });
    writeFileSync(file.path, file.content);
  }
}

await runCli(() => {
  const names = getComponentNames(process.argv[2]);
  const componentDir = resolve(root, 'packages/vue/src/components', names.kebab);
  const docsFile = resolve(root, 'docs/components', `${names.kebab}.md`);
  const componentIndex = resolve(root, 'packages/vue/src/components/index.ts');

  const targetFiles: TargetFile[] = [
    {
      path: resolve(componentDir, `${names.kebab}.vue`),
      content: `<script setup lang="ts">
import { ${names.pascal}Props } from './props';

defineOptions({
  name: 'Custom${names.pascal}'
});

defineProps(${names.pascal}Props);
</script>

<template>
  <div class="custom-${names.kebab}">
    <slot />
  </div>
</template>
`
    },
    {
      path: resolve(componentDir, 'props.ts'),
      content: `import type { PropType } from 'vue';

export const ${names.pascal}Props = {
  /** 显示变体，请根据组件真实语义调整 */
  variant: {
    type: String as PropType<'default' | 'primary'>,
    default: 'default'
  }
} as const;
`
    },
    {
      path: resolve(componentDir, 'index.ts'),
      content: `export { default as Custom${names.pascal} } from './${names.kebab}.vue';
export * from './props';
`
    },
    {
      path: resolve(componentDir, 'demo/basic.vue'),
      content: `<script setup lang="ts">
import { Custom${names.pascal} } from '../index';
</script>

<template>
  <Custom${names.pascal}>Basic ${names.pascal}</Custom${names.pascal}>
</template>
`
    },
    {
      path: resolve(componentDir, `__tests__/${names.kebab}.test.ts`),
      content: `import { describe, expect, it } from 'vitest';

import { Custom${names.pascal} } from '../index';

describe('Custom${names.pascal}', () => {
  it('exports the component', () => {
    expect(Custom${names.pascal}).toBeTruthy();
  });
});
`
    },
    {
      path: docsFile,
      content: `# ${names.pascal}

## 基础用法

<!-- DemoBlock wiring is completed by docs-writer after the component implementation is finalized. -->

## API

<!-- API table is generated by pnpm generate-api ${names.pascal}. -->
`
    }
  ];

  writeTargetFiles(targetFiles);

  const currentIndex = readFileSync(componentIndex, 'utf8');
  const exportLine = `export * from './${names.kebab}';`;

  if (!currentIndex.includes(exportLine)) {
    writeFileSync(componentIndex, `${currentIndex.trim()}\n${exportLine}\n`);
  }

  console.log(`Created component scaffold for ${names.pascal}.`);
});
